fastqdumpdir: data/ncbi_thaps_fastqs
fastqdir: data/interleaved_ncbi
trimmedfastqdir: data/trimmed_output
trimmedfastqdirintermed: data/trimmed_output_intermed
baddir: data/bad_from_afterqc
outputsourmash: data/sourmash_sigs
trinityoutputdir: data/trinity_output
trinityfastadir: data/trinity_output/trinityfiles
startingdir: data/ncbi_thaps_fastqs
startingextension: .fastq
outputcomparison: data/cmp_sourmash
transdecoder: data/transdecoder
backtrans: data/backtransseq
backtranssig: data/backtranssig
referencenames: 
    - thapsreference
    - thapsreferencecoding
    - pseudreference
    - pseudreferencecoding
    - fragreference
    - fragreferencecoding
outputname: TP_PN_FG_exp