channels:
        - bioconda
        - conda-forge
dependencies:
        - python = 3.6.9
        - trinity = 2.8.5
        - salmon = 1.1.0
        - sourmash = 3.1.0
        - snakemake = 5.3.0
        - networkx = 2.1
        - matplotlib 
        - fastqc = 0.11.8
        - afterqc
        - seqtk
        - khmer
